site_name: Infinity
site_url: https://michaelfeil.github.io/infinity/
repo_url: https://github.com/michaelfeil/infinity/
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
extra:
  version:
    provider: mike

plugins:
   - swagger-ui-tag:
        background: White
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences